apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: magikup

resources:
  - rbac.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - networkpolicy.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
